// PayslipIQ USA - Per-state gross-to-net config (51 entries: 50 states + DC)
// Used by /us/gross-to-net-paycheck/[state]/ programmatic pages.
// Verified 2026-05-06. Educational only. Not advice.
//
// Sources:
//   IRS Pub 15-T 2026 (federal)
//   SSA Contribution and Benefit Base 2026 (FICA wage base)
//   State revenue/labor agencies linked per row
//
// Notes on rate selection:
//   - "rate" is a flat or top-marginal effective rate appropriate for ~$60-100k earners
//   - States with brackets use a rate that matches mid-bracket workers
//   - Worker contributions (SDI, PFML, FAMLI, WA Cares, etc.) are NOT included in "rate"
//     and are documented in workerContributions for narrative use

export interface StateGrossToNetEntry {
  code: string;
  name: string;
  slug: string;
  rate: number;             // state income tax effective rate (flat or top-marginal mid-bracket)
  noIncomeTax: boolean;
  hasFlatTax: boolean;
  hasBrackets: boolean;
  hasLocalTax: boolean;     // local income tax exists in some cities/counties
  hasSDI: boolean;          // state disability insurance worker contribution
  hasPFML: boolean;         // paid family/medical leave worker contribution
  workerContributions: string[];
  revenueAgency: { name: string; url: string };
  laborAgency: { name: string; url: string };
  paycheckCalculator: string; // link to state's official calc if any (else state revenue page)
  notes: string;
}

export const STATE_CONFIGS: StateGrossToNetEntry[] = [
  { code: 'AL', name: 'Alabama', slug: 'alabama', rate: 0.05, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: true, hasSDI: false, hasPFML: false, workerContributions: ['SUI (employer-paid in AL)'], revenueAgency: { name: 'Alabama Department of Revenue', url: 'https://revenue.alabama.gov/' }, laborAgency: { name: 'Alabama Department of Labor', url: 'https://labor.alabama.gov/' }, paycheckCalculator: 'https://revenue.alabama.gov/individual-corporate/withholding-tax/', notes: 'Some cities (Birmingham, Bessemer, etc.) levy occupational license fees that act like local income tax.' },
  { code: 'AK', name: 'Alaska', slug: 'alaska', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: ['UI worker contribution (small)'], revenueAgency: { name: 'Alaska Department of Revenue', url: 'https://www.tax.alaska.gov/' }, laborAgency: { name: 'Alaska Department of Labor and Workforce Development', url: 'https://labor.alaska.gov/' }, paycheckCalculator: 'https://labor.alaska.gov/estax/', notes: 'No state income tax on wages. Alaska does have a Permanent Fund Dividend.' },
  { code: 'AZ', name: 'Arizona', slug: 'arizona', rate: 0.025, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Arizona Department of Revenue', url: 'https://azdor.gov/' }, laborAgency: { name: 'Industrial Commission of Arizona', url: 'https://www.azica.gov/' }, paycheckCalculator: 'https://azdor.gov/businesses-arizona/withholding-tax', notes: 'Flat 2.5% income tax effective 2023.' },
  { code: 'AR', name: 'Arkansas', slug: 'arkansas', rate: 0.044, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Arkansas Department of Finance and Administration', url: 'https://www.dfa.arkansas.gov/' }, laborAgency: { name: 'Arkansas Department of Labor and Licensing', url: 'https://www.labor.arkansas.gov/' }, paycheckCalculator: 'https://www.dfa.arkansas.gov/income-tax/', notes: 'Top marginal rate has been reduced over recent years.' },
  { code: 'CA', name: 'California', slug: 'california', rate: 0.066, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: true, hasSDI: true, hasPFML: false, workerContributions: ['CA SDI (1.1% no cap from 2024)', 'PFL benefits funded via SDI'], revenueAgency: { name: 'California Franchise Tax Board', url: 'https://www.ftb.ca.gov/' }, laborAgency: { name: 'California Department of Industrial Relations', url: 'https://www.dir.ca.gov/' }, paycheckCalculator: 'https://www.edd.ca.gov/Payroll_Taxes/', notes: 'CA has progressive brackets with a top rate around 13.3% (mental-health surcharge inclusive). SDI 1.1% applies to all wages with no cap as of 2024. San Francisco employers face additional payroll taxes.' },
  { code: 'CO', name: 'Colorado', slug: 'colorado', rate: 0.044, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: true, hasSDI: false, hasPFML: true, workerContributions: ['FAMLI (employee 0.45% of wages)'], revenueAgency: { name: 'Colorado Department of Revenue', url: 'https://tax.colorado.gov/' }, laborAgency: { name: 'Colorado Department of Labor and Employment', url: 'https://cdle.colorado.gov/' }, paycheckCalculator: 'https://tax.colorado.gov/withholding-tax', notes: 'Flat 4.4%. FAMLI premium 0.9% total, half employee. Some cities (Denver) have occupational privilege tax.' },
  { code: 'CT', name: 'Connecticut', slug: 'connecticut', rate: 0.055, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: true, workerContributions: ['CT Paid Leave (employee 0.5% up to SS wage base)'], revenueAgency: { name: 'CT Department of Revenue Services', url: 'https://portal.ct.gov/drs' }, laborAgency: { name: 'CT Department of Labor', url: 'https://www.ctdol.state.ct.us/' }, paycheckCalculator: 'https://portal.ct.gov/drs/individuals/individual-tax-page', notes: 'Progressive brackets. Paid Leave deduction since 2021.' },
  { code: 'DE', name: 'Delaware', slug: 'delaware', rate: 0.052, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: true, hasSDI: false, hasPFML: true, workerContributions: ['DE Paid Leave (starting 2025)'], revenueAgency: { name: 'Delaware Division of Revenue', url: 'https://revenue.delaware.gov/' }, laborAgency: { name: 'Delaware Department of Labor', url: 'https://labor.delaware.gov/' }, paycheckCalculator: 'https://revenue.delaware.gov/business-tax-forms/', notes: 'Wilmington has a 1.25% wage tax. DE Paid Leave is rolling out.' },
  { code: 'DC', name: 'District of Columbia', slug: 'district-of-columbia', rate: 0.065, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: true, workerContributions: ['DC Paid Family Leave (employer-paid 0.26%, no employee deduction)'], revenueAgency: { name: 'DC Office of Tax and Revenue', url: 'https://otr.cfo.dc.gov/' }, laborAgency: { name: 'DC Department of Employment Services', url: 'https://does.dc.gov/' }, paycheckCalculator: 'https://otr.cfo.dc.gov/page/withholding-tax', notes: 'Progressive brackets up to 10.75%. PFL employer-funded.' },
  { code: 'FL', name: 'Florida', slug: 'florida', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Florida Department of Revenue', url: 'https://floridarevenue.com/' }, laborAgency: { name: 'Florida Department of Commerce', url: 'https://www.commerce.fl.gov/' }, paycheckCalculator: 'https://floridarevenue.com/taxes/Pages/default.aspx', notes: 'No state income tax on wages.' },
  { code: 'GA', name: 'Georgia', slug: 'georgia', rate: 0.0539, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Georgia Department of Revenue', url: 'https://dor.georgia.gov/' }, laborAgency: { name: 'Georgia Department of Labor', url: 'https://dol.georgia.gov/' }, paycheckCalculator: 'https://dor.georgia.gov/taxes/withholding-tax', notes: 'Moved to flat tax effective 2024.' },
  { code: 'HI', name: 'Hawaii', slug: 'hawaii', rate: 0.072, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: true, hasPFML: false, workerContributions: ['HI TDI (0.5% up to weekly cap)'], revenueAgency: { name: 'Hawaii Department of Taxation', url: 'https://tax.hawaii.gov/' }, laborAgency: { name: 'Hawaii Department of Labor and Industrial Relations', url: 'https://labor.hawaii.gov/' }, paycheckCalculator: 'https://tax.hawaii.gov/forms/', notes: 'Top marginal 11%. TDI worker share 0.5%.' },
  { code: 'ID', name: 'Idaho', slug: 'idaho', rate: 0.058, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Idaho State Tax Commission', url: 'https://tax.idaho.gov/' }, laborAgency: { name: 'Idaho Department of Labor', url: 'https://www.labor.idaho.gov/' }, paycheckCalculator: 'https://tax.idaho.gov/i-1098.cfm', notes: 'Flat tax effective recently.' },
  { code: 'IL', name: 'Illinois', slug: 'illinois', rate: 0.0495, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Illinois Department of Revenue', url: 'https://tax.illinois.gov/' }, laborAgency: { name: 'Illinois Department of Labor', url: 'https://labor.illinois.gov/' }, paycheckCalculator: 'https://tax.illinois.gov/programs/withholding.html', notes: 'Flat 4.95%. Chicago has separate ordinances.' },
  { code: 'IN', name: 'Indiana', slug: 'indiana', rate: 0.0305, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: true, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Indiana Department of Revenue', url: 'https://www.in.gov/dor/' }, laborAgency: { name: 'Indiana Department of Labor', url: 'https://www.in.gov/dol/' }, paycheckCalculator: 'https://www.in.gov/dor/business-tax/withholding-income-tax/', notes: 'Flat state + every county has its own piggyback.' },
  { code: 'IA', name: 'Iowa', slug: 'iowa', rate: 0.038, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Iowa Department of Revenue', url: 'https://tax.iowa.gov/' }, laborAgency: { name: 'Iowa Workforce Development', url: 'https://www.iowaworkforcedevelopment.gov/' }, paycheckCalculator: 'https://tax.iowa.gov/withholding-tax-information', notes: 'Iowa moved to flat tax structure.' },
  { code: 'KS', name: 'Kansas', slug: 'kansas', rate: 0.052, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Kansas Department of Revenue', url: 'https://www.ksrevenue.gov/' }, laborAgency: { name: 'Kansas Department of Labor', url: 'https://www.dol.ks.gov/' }, paycheckCalculator: 'https://www.ksrevenue.gov/bustaxtypeswh.html', notes: 'Brackets up to 5.7%.' },
  { code: 'KY', name: 'Kentucky', slug: 'kentucky', rate: 0.04, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: true, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Kentucky Department of Revenue', url: 'https://revenue.ky.gov/' }, laborAgency: { name: 'Kentucky Labor Cabinet', url: 'https://labor.ky.gov/' }, paycheckCalculator: 'https://revenue.ky.gov/Business/Pages/Withholding-Tax.aspx', notes: 'Flat 4%. Many counties and cities levy occupational license tax.' },
  { code: 'LA', name: 'Louisiana', slug: 'louisiana', rate: 0.03, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Louisiana Department of Revenue', url: 'https://revenue.louisiana.gov/' }, laborAgency: { name: 'Louisiana Workforce Commission', url: 'https://www.laworks.net/' }, paycheckCalculator: 'https://revenue.louisiana.gov/IndividualIncomeTax', notes: 'Moved to flat 3% effective 2025.' },
  { code: 'ME', name: 'Maine', slug: 'maine', rate: 0.058, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: true, workerContributions: ['ME Paid Family Leave (starting 2026)'], revenueAgency: { name: 'Maine Revenue Services', url: 'https://www.maine.gov/revenue/' }, laborAgency: { name: 'Maine Department of Labor', url: 'https://www.maine.gov/labor/' }, paycheckCalculator: 'https://www.maine.gov/revenue/taxes/income-estate-tax/withholding-tax', notes: 'Top marginal 7.15%. PFL premium starts 2026.' },
  { code: 'MD', name: 'Maryland', slug: 'maryland', rate: 0.0475, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: true, hasSDI: false, hasPFML: true, workerContributions: ['MD FAMLI (employee share TBD, starting 2026)'], revenueAgency: { name: 'Comptroller of Maryland', url: 'https://www.marylandtaxes.gov/' }, laborAgency: { name: 'Maryland Department of Labor', url: 'https://www.dllr.state.md.us/' }, paycheckCalculator: 'https://www.marylandtaxes.gov/business/income/withholding/', notes: 'State + every county piggybacks (2.25-3.2%).' },
  { code: 'MA', name: 'Massachusetts', slug: 'massachusetts', rate: 0.05, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: true, workerContributions: ['MA PFML (employee 0.318% medical + 0.18% family on 2024 figures)'], revenueAgency: { name: 'Massachusetts Department of Revenue', url: 'https://www.mass.gov/orgs/massachusetts-department-of-revenue' }, laborAgency: { name: 'Massachusetts Executive Office of Labor and Workforce Development', url: 'https://www.mass.gov/orgs/executive-office-of-labor-and-workforce-development' }, paycheckCalculator: 'https://www.mass.gov/topics/withholding-tax', notes: 'Flat 5%. 4% surtax on income over $1M (Fair Share Amendment).' },
  { code: 'MI', name: 'Michigan', slug: 'michigan', rate: 0.0425, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: true, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Michigan Department of Treasury', url: 'https://www.michigan.gov/treasury' }, laborAgency: { name: 'Michigan Department of Labor and Economic Opportunity', url: 'https://www.michigan.gov/leo' }, paycheckCalculator: 'https://www.michigan.gov/taxes/business-taxes/withholding', notes: 'Flat 4.25%. Detroit and ~22 cities levy income tax.' },
  { code: 'MN', name: 'Minnesota', slug: 'minnesota', rate: 0.068, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: true, workerContributions: ['MN Paid Family and Medical Leave (starting 2026)'], revenueAgency: { name: 'Minnesota Department of Revenue', url: 'https://www.revenue.state.mn.us/' }, laborAgency: { name: 'Minnesota Department of Labor and Industry', url: 'https://www.dli.mn.gov/' }, paycheckCalculator: 'https://www.revenue.state.mn.us/withholding-tax', notes: 'Brackets up to 9.85%. PFML premium starts 2026.' },
  { code: 'MS', name: 'Mississippi', slug: 'mississippi', rate: 0.044, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Mississippi Department of Revenue', url: 'https://www.dor.ms.gov/' }, laborAgency: { name: 'Mississippi Department of Employment Security', url: 'https://mdes.ms.gov/' }, paycheckCalculator: 'https://www.dor.ms.gov/business/withholding-taxes', notes: 'Flat 4.4%, scheduled to drop further.' },
  { code: 'MO', name: 'Missouri', slug: 'missouri', rate: 0.047, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: true, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Missouri Department of Revenue', url: 'https://dor.mo.gov/' }, laborAgency: { name: 'Missouri Department of Labor', url: 'https://labor.mo.gov/' }, paycheckCalculator: 'https://dor.mo.gov/business/withholding/', notes: 'Top 4.7%. Kansas City and St. Louis 1% earnings tax.' },
  { code: 'MT', name: 'Montana', slug: 'montana', rate: 0.059, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Montana Department of Revenue', url: 'https://mtrevenue.gov/' }, laborAgency: { name: 'Montana Department of Labor and Industry', url: 'https://dli.mt.gov/' }, paycheckCalculator: 'https://mtrevenue.gov/taxes/wage-withholding/', notes: 'Two-bracket structure.' },
  { code: 'NE', name: 'Nebraska', slug: 'nebraska', rate: 0.052, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Nebraska Department of Revenue', url: 'https://revenue.nebraska.gov/' }, laborAgency: { name: 'Nebraska Department of Labor', url: 'https://dol.nebraska.gov/' }, paycheckCalculator: 'https://revenue.nebraska.gov/businesses/withholding', notes: 'Brackets up to ~5.84%, dropping over time.' },
  { code: 'NV', name: 'Nevada', slug: 'nevada', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Nevada Department of Taxation', url: 'https://tax.nv.gov/' }, laborAgency: { name: 'Nevada Department of Business and Industry', url: 'https://labor.nv.gov/' }, paycheckCalculator: 'https://tax.nv.gov/', notes: 'No state income tax on wages.' },
  { code: 'NH', name: 'New Hampshire', slug: 'new-hampshire', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'New Hampshire Department of Revenue Administration', url: 'https://www.revenue.nh.gov/' }, laborAgency: { name: 'New Hampshire Department of Labor', url: 'https://www.nh.gov/labor/' }, paycheckCalculator: 'https://www.revenue.nh.gov/', notes: 'No tax on wage income (interest/dividends tax fully repealed).' },
  { code: 'NJ', name: 'New Jersey', slug: 'new-jersey', rate: 0.058, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: true, hasPFML: true, workerContributions: ['NJ TDI (employee share, varies)', 'NJ FLI (~0.06%)', 'NJ UI worker contribution'], revenueAgency: { name: 'NJ Division of Taxation', url: 'https://www.state.nj.us/treasury/taxation/' }, laborAgency: { name: 'NJ Department of Labor and Workforce Development', url: 'https://www.nj.gov/labor/' }, paycheckCalculator: 'https://www.state.nj.us/treasury/taxation/njit11.shtml', notes: 'Brackets up to 10.75%. Stub typically shows 4 small worker-contribution lines.' },
  { code: 'NM', name: 'New Mexico', slug: 'new-mexico', rate: 0.049, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'New Mexico Taxation and Revenue Department', url: 'https://www.tax.newmexico.gov/' }, laborAgency: { name: 'New Mexico Department of Workforce Solutions', url: 'https://www.dws.state.nm.us/' }, paycheckCalculator: 'https://www.tax.newmexico.gov/businesses/wage-withholding-tax/', notes: 'Brackets up to ~5.9%.' },
  { code: 'NY', name: 'New York', slug: 'new-york', rate: 0.06, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: true, hasSDI: true, hasPFML: true, workerContributions: ['NY SDI (employee share via PFL premium and TDI)', 'NY PFL (~0.373% capped)'], revenueAgency: { name: 'NY Department of Taxation and Finance', url: 'https://www.tax.ny.gov/' }, laborAgency: { name: 'NY State Department of Labor', url: 'https://dol.ny.gov/' }, paycheckCalculator: 'https://www.tax.ny.gov/bus/wt/wthd_lng.htm', notes: 'Brackets up to ~10.9%. NYC and Yonkers add resident income tax.' },
  { code: 'NC', name: 'North Carolina', slug: 'north-carolina', rate: 0.0425, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'NC Department of Revenue', url: 'https://www.ncdor.gov/' }, laborAgency: { name: 'NC Department of Labor', url: 'https://www.labor.nc.gov/' }, paycheckCalculator: 'https://www.ncdor.gov/taxes-forms/withholding-tax', notes: 'Flat 4.25%, scheduled to drop further.' },
  { code: 'ND', name: 'North Dakota', slug: 'north-dakota', rate: 0.025, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'ND Office of State Tax Commissioner', url: 'https://www.tax.nd.gov/' }, laborAgency: { name: 'ND Department of Labor and Human Rights', url: 'https://www.nd.gov/labor/' }, paycheckCalculator: 'https://www.tax.nd.gov/business/income-tax-withholding', notes: 'Three-bracket structure with low rates.' },
  { code: 'OH', name: 'Ohio', slug: 'ohio', rate: 0.035, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: true, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Ohio Department of Taxation', url: 'https://tax.ohio.gov/' }, laborAgency: { name: 'Ohio Department of Commerce', url: 'https://com.ohio.gov/' }, paycheckCalculator: 'https://tax.ohio.gov/business/ohio-business-taxes/employer-withholding-tax', notes: 'State brackets up to ~3.5%. RITA / CCA cities levy 1-3% local tax.' },
  { code: 'OK', name: 'Oklahoma', slug: 'oklahoma', rate: 0.0475, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Oklahoma Tax Commission', url: 'https://oklahoma.gov/tax.html' }, laborAgency: { name: 'Oklahoma Department of Labor', url: 'https://oklahoma.gov/labor.html' }, paycheckCalculator: 'https://oklahoma.gov/tax/businesses/income-tax-withholding.html', notes: 'Top marginal 4.75%.' },
  { code: 'OR', name: 'Oregon', slug: 'oregon', rate: 0.087, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: true, hasSDI: false, hasPFML: true, workerContributions: ['Oregon Statewide Transit Tax (0.1% on all wages)', 'Paid Leave Oregon (~0.6% employee)'], revenueAgency: { name: 'Oregon Department of Revenue', url: 'https://www.oregon.gov/dor/' }, laborAgency: { name: 'Oregon Bureau of Labor and Industries', url: 'https://www.oregon.gov/boli/' }, paycheckCalculator: 'https://www.oregon.gov/dor/programs/businesses/Pages/Withholding.aspx', notes: 'Top bracket 9.9%. Multnomah/Metro have local income taxes for high earners.' },
  { code: 'PA', name: 'Pennsylvania', slug: 'pennsylvania', rate: 0.0307, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: true, hasSDI: false, hasPFML: false, workerContributions: ['PA UI worker contribution (0.07%)'], revenueAgency: { name: 'PA Department of Revenue', url: 'https://www.revenue.pa.gov/' }, laborAgency: { name: 'PA Department of Labor and Industry', url: 'https://www.dli.pa.gov/' }, paycheckCalculator: 'https://www.revenue.pa.gov/EmployerTaxInformation/Pages/default.aspx', notes: 'Flat state 3.07%. Every municipality has EIT (Earned Income Tax) under Act 32, plus LST (Local Services Tax) typically $52/year.' },
  { code: 'RI', name: 'Rhode Island', slug: 'rhode-island', rate: 0.0499, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: true, hasPFML: true, workerContributions: ['RI TDI (1.2% up to wage cap)', 'RI TCI (within TDI)'], revenueAgency: { name: 'RI Division of Taxation', url: 'https://tax.ri.gov/' }, laborAgency: { name: 'RI Department of Labor and Training', url: 'https://dlt.ri.gov/' }, paycheckCalculator: 'https://tax.ri.gov/forms-publications/withholding-tax-forms', notes: 'Brackets up to 5.99%. TDI is one of the highest worker contributions in the US.' },
  { code: 'SC', name: 'South Carolina', slug: 'south-carolina', rate: 0.062, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'SC Department of Revenue', url: 'https://dor.sc.gov/' }, laborAgency: { name: 'SC Department of Labor, Licensing and Regulation', url: 'https://www.llr.sc.gov/' }, paycheckCalculator: 'https://dor.sc.gov/tax/withholding', notes: 'Top bracket ~6.4%, scheduled to drop further.' },
  { code: 'SD', name: 'South Dakota', slug: 'south-dakota', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'SD Department of Revenue', url: 'https://dor.sd.gov/' }, laborAgency: { name: 'SD Department of Labor and Regulation', url: 'https://dlr.sd.gov/' }, paycheckCalculator: 'https://dor.sd.gov/', notes: 'No state income tax on wages.' },
  { code: 'TN', name: 'Tennessee', slug: 'tennessee', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Tennessee Department of Revenue', url: 'https://www.tn.gov/revenue.html' }, laborAgency: { name: 'TN Department of Labor and Workforce Development', url: 'https://www.tn.gov/workforce.html' }, paycheckCalculator: 'https://www.tn.gov/revenue.html', notes: 'No tax on wage income (Hall income tax fully repealed).' },
  { code: 'TX', name: 'Texas', slug: 'texas', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Texas Comptroller of Public Accounts', url: 'https://comptroller.texas.gov/' }, laborAgency: { name: 'Texas Workforce Commission', url: 'https://www.twc.texas.gov/' }, paycheckCalculator: 'https://www.twc.texas.gov/programs/unemployment-tax', notes: 'No state income tax on wages.' },
  { code: 'UT', name: 'Utah', slug: 'utah', rate: 0.0455, noIncomeTax: false, hasFlatTax: true, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Utah State Tax Commission', url: 'https://tax.utah.gov/' }, laborAgency: { name: 'Utah Labor Commission', url: 'https://laborcommission.utah.gov/' }, paycheckCalculator: 'https://tax.utah.gov/withholding', notes: 'Flat 4.55%.' },
  { code: 'VT', name: 'Vermont', slug: 'vermont', rate: 0.066, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Vermont Department of Taxes', url: 'https://tax.vermont.gov/' }, laborAgency: { name: 'Vermont Department of Labor', url: 'https://labor.vermont.gov/' }, paycheckCalculator: 'https://tax.vermont.gov/business/withholding', notes: 'Top bracket ~8.75%.' },
  { code: 'VA', name: 'Virginia', slug: 'virginia', rate: 0.0525, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Virginia Department of Taxation', url: 'https://www.tax.virginia.gov/' }, laborAgency: { name: 'Virginia Department of Labor and Industry', url: 'https://www.doli.virginia.gov/' }, paycheckCalculator: 'https://www.tax.virginia.gov/withholding-tax', notes: 'Top bracket 5.75%.' },
  { code: 'WA', name: 'Washington', slug: 'washington', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: true, workerContributions: ['WA Paid Family and Medical Leave (~0.42% employee 2025)', 'WA Cares Fund (0.58% on all wages, opt-out limited)'], revenueAgency: { name: 'WA Department of Revenue', url: 'https://dor.wa.gov/' }, laborAgency: { name: 'WA Department of Labor and Industries', url: 'https://www.lni.wa.gov/' }, paycheckCalculator: 'https://www.lni.wa.gov/', notes: 'No state income tax on wages but two significant worker-contribution programs.' },
  { code: 'WV', name: 'West Virginia', slug: 'west-virginia', rate: 0.0482, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'WV State Tax Department', url: 'https://tax.wv.gov/' }, laborAgency: { name: 'WV Division of Labor', url: 'https://labor.wv.gov/' }, paycheckCalculator: 'https://tax.wv.gov/Business/Withholding/', notes: 'Brackets up to ~6.5%, recently reduced.' },
  { code: 'WI', name: 'Wisconsin', slug: 'wisconsin', rate: 0.0535, noIncomeTax: false, hasFlatTax: false, hasBrackets: true, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Wisconsin Department of Revenue', url: 'https://www.revenue.wi.gov/' }, laborAgency: { name: 'Wisconsin Department of Workforce Development', url: 'https://dwd.wisconsin.gov/' }, paycheckCalculator: 'https://www.revenue.wi.gov/Pages/Businesses/Withholding-Tax.aspx', notes: 'Top bracket 7.65%.' },
  { code: 'WY', name: 'Wyoming', slug: 'wyoming', rate: 0, noIncomeTax: true, hasFlatTax: false, hasBrackets: false, hasLocalTax: false, hasSDI: false, hasPFML: false, workerContributions: [], revenueAgency: { name: 'Wyoming Department of Revenue', url: 'https://revenue.wyo.gov/' }, laborAgency: { name: 'Wyoming Department of Workforce Services', url: 'https://dws.wyo.gov/' }, paycheckCalculator: 'https://revenue.wyo.gov/', notes: 'No state income tax on wages.' }
];

export function getStateConfig(slug: string): StateGrossToNetEntry | undefined {
  return STATE_CONFIGS.find((s) => s.slug === slug);
}

export const STATE_SLUGS = STATE_CONFIGS.map((s) => s.slug);
